### ISSUE TITLE
valideringsreglene for epostadresse er feil

### ISSUE THREAD

**Issue by aberner** [difi/begrep-Felles#2]
Det regulære uttrykket dokumentert her: http://begrep.difi.no/Felles/epostadresse er ikke det som lenger blir brukt.
Implementasjonen er endret ettersom standarden for epostadresser er utvidet og støtter bruk av internasjonale tegn.

Det er nå følgende åpne kildekode som brukes for validering av epostadresser: 
http://svn.apache.org/viewvc/commons/proper/validator/tags/VALIDATOR_1_4_1/src/main/java/org/apache/commons/validator/routines/EmailValidator.java?view=markup

**Comment by holgerl** [comment]
Det regulære uttrykket som ligger der nå går ikke an å kompilere. Det er ikke et gyldig regulært uttrykk.

**Comment by aberner** [comment]
det dokumenterte regulære uttrykket er uansett ikke lenger i bruk og er erstattet av apache commons sin Emailvalidator. 
Det som gjør dette litt vanskelig er å dokumentere valideringsreglene som er i apache commons.

Det som gjør dette ekstra vanskelig er at det heller ikke er spesielt enkelt å peke på den standard som definerer reglene for e-post adresser. Reglene for e-postadresser er styrt etter flere forskjellige standarder og er ikke helt enkelt å dokumentere.

**Comment by holgerl** [comment]
Da bør virkelig det som står på denne siden endres: http://begrep.difi.no/Felles/epostadresse 

Det står ingenting der om at den ikke er i bruk eller hva som erstatter den.

**Comment by aberner** [comment]
ja, det er riktig. jeg legger ut en endring om ikke så alt for lenge.

**Comment by aberner** [comment]
Da har jeg forsøkt oppdatere dokumentasjonen. http://begrep.difi.no/Felles/epostadresse skal bli oppdatert automatisk når jeg nå har fikset dette. (må nok vente 10 - 30 min)

**Comment by aberner** [comment]
http://begrep.difi.no/Felles/epostadresse er nå oppdatert.

**Comment by aberner** [comment]
dokumentasjonen er nå oppdatert og i tråd med det som er implementert.
